2021-07-26 09:39:25,193 ERROR: Exception on /search [GET] [in d:\py\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "d:\py\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\py\microblog\app\main\routes.py", line 182, in search
    return render_template(
  File "d:\py\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "d:\py\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "d:\py\microblog\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "d:\py\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\py\microblog\app\templates\search.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\py\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "d:\py\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "d:\py\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "d:\py\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "d:\py\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "D:\py\microblog\app\templates\base.html", line 57, in block 'content'
    {% block app_content %}{% endblock %}
  File "D:\py\microblog\app\templates\search.html", line 8, in block 'app_content'
    _(
  File "d:\py\microblog\venv\lib\site-packages\jinja2\ext.py", line 168, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "d:\py\microblog\venv\lib\site-packages\jinja2\ext.py", line 180, in gettext
    return rv % variables  # type: ignore
  File "d:\py\microblog\venv\lib\site-packages\markupsafe\__init__.py", line 109, in __mod__
    return self.__class__(super().__mod__(arg))
TypeError: %d format: a number is required, not _MarkupEscapeHelper
2021-07-26 09:39:48,655 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:90]
2021-07-26 09:40:21,684 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:90]
2021-07-26 09:40:24,353 ERROR: Exception on /search [GET] [in d:\py\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "d:\py\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\py\microblog\app\main\routes.py", line 168, in search
    posts, total = Post.search(
  File "D:\py\microblog\app\models.py", line 14, in search
    ids, total = query_index(
  File "D:\py\microblog\app\search.py", line 28, in query_index
    search = current_app.elasticsearch.search(
  File "d:\py\microblog\venv\lib\site-packages\elasticsearch\client\utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "d:\py\microblog\venv\lib\site-packages\elasticsearch\client\__init__.py", line 1670, in search
    return self.transport.perform_request(
  File "d:\py\microblog\venv\lib\site-packages\elasticsearch\transport.py", line 415, in perform_request
    raise e
  File "d:\py\microblog\venv\lib\site-packages\elasticsearch\transport.py", line 381, in perform_request
    status, headers_response, data = connection.perform_request(
  File "d:\py\microblog\venv\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 277, in perform_request
    self._raise_error(response.status, raw_data)
  File "d:\py\microblog\venv\lib\site-packages\elasticsearch\connection\base.py", line 330, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'number_format_exception', 'empty String')
2021-07-26 09:41:09,886 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:90]
2021-07-26 09:42:36,648 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:90]
2021-07-26 09:42:38,668 ERROR: Exception on /search [GET] [in d:\py\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "d:\py\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\py\microblog\app\main\routes.py", line 182, in search
    return render_template(
  File "d:\py\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "d:\py\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "d:\py\microblog\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "d:\py\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\py\microblog\app\templates\search.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\py\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "d:\py\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "d:\py\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "d:\py\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "d:\py\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "D:\py\microblog\app\templates\base.html", line 57, in block 'content'
    {% block app_content %}{% endblock %}
  File "D:\py\microblog\app\templates\search.html", line 8, in block 'app_content'
    _(
  File "d:\py\microblog\venv\lib\site-packages\jinja2\ext.py", line 168, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "d:\py\microblog\venv\lib\site-packages\jinja2\ext.py", line 180, in gettext
    return rv % variables  # type: ignore
  File "d:\py\microblog\venv\lib\site-packages\markupsafe\__init__.py", line 109, in __mod__
    return self.__class__(super().__mod__(arg))
TypeError: %d format: a number is required, not _MarkupEscapeHelper
2021-07-26 09:43:39,291 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:90]
