2021-07-21 21:35:30,979 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:54]
2021-07-21 21:39:48,227 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:54]
2021-07-21 21:42:24,793 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:54]
2021-07-21 21:46:40,930 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:54]
2021-07-22 00:45:47,002 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:54]
2021-07-22 00:54:59,269 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:54]
2021-07-22 01:05:10,590 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:54]
2021-07-22 01:05:20,045 ERROR: Exception on /user/paphra [GET] [in d:\py\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "d:\py\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\py\microblog\app\routes.py", line 117, in user
    next_url = url_for('user', user.username, page=posts.next_num) if posts.has_next else None
TypeError: url_for() takes 1 positional argument but 2 were given
2021-07-22 01:07:03,407 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:54]
2021-07-22 01:07:06,798 ERROR: Exception on /user/paphra [GET] [in d:\py\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "d:\py\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\py\microblog\app\routes.py", line 120, in user
    return render_template(
  File "d:\py\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "d:\py\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "d:\py\microblog\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "d:\py\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\py\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\py\microblog\app\templates\base.html", line 36, in top-level template code
    {% block content %}
  File "D:\py\microblog\app\templates\user.html", line 43, in block 'content'
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2021-07-22 01:07:30,218 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:54]
